name: Fusionpact DevOps CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fusionpact-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fusionpact-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          # FIX: The key is passed directly from secrets. No need for files.
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            echo "✅ Connection successful! Starting deployment..."
            # Ensure the project directory exists
            cd /home/${{ secrets.DEPLOY_USER }}/fusionpact-devops-challenge || git clone https://github.com/${{ github.repository }} /home/${{ secrets.DEPLOY_USER }}/fusionpact-devops-challenge
            cd /home/${{ secrets.DEPLOY_USER }}/fusionpact-devops-challenge

            # Pull latest changes and run services
            git pull origin main
            docker-compose pull
            docker-compose up -d --remove-orphans
            docker image prune -f
            echo "🚀 Deployment finished!"